//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LI_Milica_Karetic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JMBG { get; set; }
        public string HealthInsuranceNumber { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> SickLeaveID { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblSickLeave tblSickLeave { get; set; }
    }
}
